  INF  Platform/EFI_Binaries/Drivers/sm6150/EnvDxe/EnvDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/SmemDxe/SmemDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/DALSYSDxe/DALSYSDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/HWIODxe/HWIODxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ChipInfoDxe/ChipInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/PlatformInfoDxe/PlatformInfoDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/HALIOMMUDxe/HALIOMMUDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ULogDxe/ULogDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/CmdDbDxe/CmdDbDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/NpaDxe/NpaDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/RpmhDxe/RpmhDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/PdcDxe/PdcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ClockDxe/ClockDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/UFSDxe/UFSDxe.inf
  #INF  Platform/EFI_Binaries/Drivers/sm6150/SdccDxe/SdccDxe.inf
  
  INF  MdeModulePkg/Bus/Sd/SdDxe/SdDxe.inf
  INF  MdeModulePkg/Bus/Sd/EmmcDxe/EmmcDxe.inf
  INF  EmbeddedPkg/Universal/MmcDxe/MmcDxe.inf
  INF  MdeModulePkg/Bus/Pci/SdMmcPciHcDxe/SdMmcPciHcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/MsmSdMmcDxe/MsmSdMmcDxe.inf

  INF  Platform/EFI_Binaries/Drivers/sm6150/ShmBridgeDxe/ShmBridgeDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/TzDxe/ScmDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/TzDxe/TzDxeLA.inf
  #INF  Platform/EFI_Binaries/Drivers/sm6150/QcomWDogDxe/QcomWDogDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/TLMMDxe/TLMMDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/I2CDxe/I2CDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/SPMIDxe/SPMIDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/PmicDxe/PmicDxeLa.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/AdcDxe/AdcDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/QcomBds/QcomBds.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/DisplayDxe/DisplayDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/QcomChargerDxe/QcomChargerDxeLA.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/ChargerExDxe/ChargerExDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbConfigDxe/UsbConfigDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbDeviceDxe/UsbDeviceDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/HashDxe/HashDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/RNGDxe/RngDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/TsensDxe/TsensDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/UsbMsdDxe/UsbMsdDxe.inf
  
  INF  Platform/EFI_Binaries/Drivers/sm6150/GpiDxe/GpiDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/PILDxe/PILDxe.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/DDRInfoDxe/DDRInfoDxe.inf
 
  INF  Platform/EFI_Binaries/Drivers/sm6150/SPI/SPI.inf
  INF  Platform/EFI_Binaries/Drivers/sm6150/FontDxe/FontDxe.inf
  
  INF Platform/EFI_Binaries/Drivers/sm6150/SecRSADxe/SecRSADxe.inf
  INF Platform/EFI_Binaries/Drivers/sm6150/ASN1X509Dxe/ASN1X509Dxe.inf
  INF Platform/EFI_Binaries/Drivers/sm6150/VerifiedBootDxe/VerifiedBootDxe.inf
  
  #INF Silicon/Qualcomm/QcomPkg/Drivers/SynapticsRmi4Dxe/SynapticsTouchDevice.inf
  #INF Silicon/Qualcomm/QcomPkg/Drivers/SynapticsRmi4Dxe/SynapticsTouchDxe.inf

  #INF Silicon/Qualcomm/QcomPkg/Drivers/SynapticsTCMDxe/SynapticsTCMDevice.inf
  #INF Silicon/Qualcomm/QcomPkg/Drivers/SynapticsTCMDxe/SynapticsTCMDxe.inf
  
  INF Silicon/Qualcomm/QcomPkg/Drivers/NovatekTouchDxe/NovatekNvtTsDevice.inf
  INF Silicon/Qualcomm/QcomPkg/Drivers/NovatekTouchDxe/NovatekNvtTs.inf
  
  INF extras/QcomUsbSerialDxe/QcomUsbSerialDxe.inf
  INF MdeModulePkg/Bus/I2c/I2cDxe/I2cDxe.inf
