# Auto-generated by /media/sasmi/3654C51954C4DD2D1/android-firmware-qti-sdm670/boot_images/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/media/sasmi/3654C51954C4DD2D1/android-firmware-qti-sdm670/boot_images
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/media/sasmi/3654C51954C4DD2D1/android-firmware-qti-sdm670/boot_images/BaseTools
fi
if [ -e /media/sasmi/3654C51954C4DD2D1/android-firmware-qti-sdm670/boot_images/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//media/sasmi/3654C51954C4DD2D1/android-firmware-qti-sdm670/boot_images/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/media/sasmi/3654C51954C4DD2D1/android-firmware-qti-sdm670/boot_images/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
